# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_user',
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coursemodules',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='module',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseEnrollment',
        ),
        migrations.DeleteModel(
            name='CourseModules',
        ),
        migrations.DeleteModel(
            name='CourseProgress',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
